- id: '1581650194668'
  alias: Fraser Arriving At Work
  description: ''
  trigger:
  - entity_id: person.fraser
    event: enter
    platform: zone
    zone: zone.work
  condition:
  - condition: or
    conditions:
    - after: 06:30:00
      before: 08:00:00
      condition: time
    - after: '18:00:00'
      before: '21:30:00'
      condition: time
  action:
  - data:
      message: Fraser Has Arrived At Work
    service: notify.mobile_app_sm_g960f
