
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
frontend:
  themes: !include_dir_merge_named themes

http:
   base_url: !secret url

lovelace:
  mode: yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use
        arg: /home
      - type: memory_free
      - type: memory_use
      - type: last_boot
      - type: processor_use

  - platform: version
  - platform: uptime 
 
  - platform: waqi
    token: !secret waqi
    locations:
      - dundee

  - platform: openhardwaremonitor
    host: 192.168.0.19
    
  - platform: template
    sensors:
     ps4_game:
         friendly_name: "Playstation 4 Now Playing"
         value_template: "{{ state_attr('media_player.playstation_4', 'media_title') }}"
  - platform: template 
    sensors: 
      xbox_one:
         value_template: "{% if is_state('device_tracker.xboxone', 'home') %}Online{% else %}Offline{% endif %}"

  - platform: fitbit
    clock_format: 24H
    monitored_resources:
      - "body/weight"
      - "activities/tracker/steps"
      - "activities/heart"


        

    
weather:
  - platform: darksky
    api_key: !secret darksky
    mode: daily

speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

spotify:
  client_id: !secret spotifyid
  client_secret: !secret spotifysecret


panel_iframe:
  tautulli:
    title: Tautulli
    icon: mdi:filmstrip
    url: http://hassio.local:8181
    
device_tracker:
  - platform: sky_hub
    host: 192.168.0.1

google:
  client_id: !secret googleid
  client_secret: !secret googlesecret

    
shopping_list:
breaking_changes:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
