background: var(--background-image)
resources:
  - url: /hacsfiles/weather-card/weather-card.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - url: /hacsfiles/unused-card/unused-card.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/swipe-card/swipe-card.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /hacsfiles/calendar-card/calendar-card.js
    type: module
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: module
  - url: /hacsfiles/banner-card/banner-card.js
    type: module
    

    
    
title: My Awesome Home
views:
  - icon: mdi:home-assistant
    path: Home
    cards:

      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: person.fraser
            show_name: false
            show_state: false
            show_info: false
            image: person.fraser
            tap_action:
                action: none
            style: |
             ha-card {
              border: solid 5px  var(--primary-color);
              border-radius: 150px;
              box-shadow: '3px 3px rgba(0,0,0,0.4)';
              overflow: hidden;
             }
          - type: picture-entity
            entity: person.julie
            show_name: false
            show_state: false
            show_info: false
            state_image:
                "home": /local/assets/people/julie.jpg
                "not_home": /local/assets/people/julie2.png
            tap_action:
                action: none
            style: |
             ha-card {
              border: solid 5px  var(--primary-color);
              border-radius: 150px;
              box-shadow: '3px 3px rgba(0,0,0,0.4)';
              overflow: hidden;
             }
             


      - type: custom:swipe-card
        cards: 
          - type: custom:mini-graph-card
            entities:
                - sensor.speedtest_download
                - sensor.speedtest_upload
            name: Speedtest
            hour24: true
            hours_to_show: 48
            lower_bound: 0
            points_per_hour: 1
            show:
              extrema: false
              fill: fade
              labels: false 
              legend: false
              average: true
          - type: custom:mini-graph-card
            entities:
                - sensor.speedtest_ping
            name: Speedtest Ping
            hour24: true
            hours_to_show: 48
            lower_bound: 0
            points_per_hour: 1
            show:
              extrema: false
              fill: fade
              labels: false 
              legend: false
              average: true

              
      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:weather-card
            entity: weather.dark_sky
            name: Dundee
            
          - type: custom:mini-graph-card
            name: Air Quality
            hours_to_show: 24
            entities:
                - sensor.waqi_dundee_broughty_ferry_road_united_kingdom
            animate: true
            decimals: 1
            align_state: center
            show:
             points: hover
             average: true
      

           
  - icon: mdi:lightbulb-on
    path: Lighting 
  

              
  
  - icon: mdi:raspberry-pi
    path: Status
    cards:
      - type: custom:vertical-stack-in-card
        title: Hass.io Status
        cards:
            - type: entities
              entities:
                - sensor.current_version
                - binary_sensor.updater
                - sensor.hacs
                - sensor.potential_breaking_changes
                - sensor.uptime
                - sensor.last_boot
                - sensor.disk_use_home

                
            - type: glance
              entities:
                - sensor.processor_use
                - sensor.memory_free
                - sensor.memory_use
            
    

                
      - type: custom:vertical-stack-in-card
        title: PC 
        align: centre
        cards: 
            - type: entities
              entities:
               - sensor.fraser_nvidia_geforce_gtx_1070_temperatures_gpu_core
               - sensor.fraser_intel_core_i7_4770k_temperatures_cpu_package
            - type: glance
              entities: 
                - sensor.fraser_generic_hard_disk_load_used_space_2
                - sensor.fraser_generic_hard_disk_load_used_space
                - sensor.fraser_sandisk_ssd_plus_480gb_load_used_space
                - sensor.fraser_samsung_ssd_850_evo_250gb_load_used_space
                - sensor.fraser_st500dm002_1bd142_load_used_space
              
      - type: custom:mini-media-player
        entity: media_player.playstation_4
        artwork: cover
        hide:
         volume: true
         source: true
         power_state: false

  - title: Automations
    path: Automations
    cards:
    
      - type: entities
        title: Notifications
        show_header_toggle: false
        entities: 

            
      - type: entities
        title: PS4 Games 
        show_header_toggle: false
        entities:
            - script.1581951130767  
            - script.1584250350664
            - script.1584250392152
            - script.1584250501993
         
  - title: Testing
    path: Testing
    cards:
    

      - type: glance
        entities:
            - device_tracker.xboxone
            - sensor.xbox_one
      
      - type: custom:mini-media-player
        entity: media_player.playstation_4
        icon: mdi:spotify
        artwork: cover
        source: icon
        hide:
            volume: true
            source: false
            power_state: false   

      - type: glance
        entities: 
          - sensor.weight
          - sensor.tracker_steps
          - sensor.resting_heart_rate
          
      - type: custom:vertical-stack-in-card
        title: PC 
        align: centre
        cards: 
            - type: entities
              entities:
               - sensor.sky_adsl_router_b_sent
               - sensor.sky_adsl_router_b_received
            - type: glance
              entities: 
                - sensor.sky_adsl_router_kib_s_sent
                - sensor.sky_adsl_router_packets_s_received
                
      - type: custom:banner-card
        entity: sensor.els_nx9_battery_health
        name: Reading light
        value: mdi:book-open-page-variant
        action:
          service: light.turn_on
          brightness: 50

              
      - type: custom:banner-card
        heading:
          - mdi:sony-playstation
          - PS4 Games
        background: "#B0C2ED"
        link: /lovelace/bathroom
        entities:
          - entity: script.1584250392152
            name: Gang Beasts
            action: 
                service: script.1584250392152
          - entity: script.1584250501993
            name: Netflix
            action: 
                service: script.1584250501993
                
      - type: custom:vertical-stack-in-card
        title: SpaceX
        cards:
            - type: entities
              entities:
                - sensor.next_launch_mission
                - binary_sensor.next_launch_confirmed
                - sensor.next_launch_day
                - sensor.next_launch_time
                - sensor.next_launch_site
                - sensor.next_launch_rocket
                - sensor.next_launch_payload
            
      - type: custom:unused-card

      
      
      