custom_header:
  compact_mode: true
background: var(--background-image)
resources:
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/unused-card/unused-card.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/swipe-card/swipe-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /local/slider-entity-row.js
    type: module
    
title: My Awesome Home
views:
  - icon: mdi:home-assistant
    path: Home
    cards:

      - type: horizontal-stack
        cards:
          - type: picture-entity
            entity: person.fraser
            show_name: false
            show_state: false
            show_info: false
            state_image:
                "home": /local/assets/people/fb2.png
                "not_home": /local/assets/people/fraser2.png
            tap_action:
                action: none
            style: |
             ha-card {
              border: solid 5px  var(--primary-color);
              border-radius: 150px;
              box-shadow: '3px 3px rgba(0,0,0,0.4)';
              overflow: hidden;
             }
          - type: picture-entity
            entity: person.julie
            show_name: false
            show_state: false
            show_info: false
            state_image:
                "home": /local/assets/people/julie.jpg
                "not_home": /local/assets/people/julie2.png
            tap_action:
                action: none
            style: |
             ha-card {
              border: solid 5px  var(--primary-color);
              border-radius: 150px;
              box-shadow: '3px 3px rgba(0,0,0,0.4)';
              overflow: hidden;
             }
             
      - type: custom:weather-card
        entity: weather.dark_sky
        name: Dundee


      - type: custom:mini-graph-card
        entities:
            - sensor.speedtest_ping
            - sensor.speedtest_upload
            - sensor.speedtest_download
        name: Speedtest
        hours_to_show: 72
        show:
         icon: false
         name: true
         state: false
         graph: bar


      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:weather-card
            entity: weather.dark_sky
            name: Dundee
            
          - type: custom:mini-graph-card
            name: Air Quality
            hours_to_show: 24
            entities:
                - sensor.waqi_dundee_broughty_ferry_road_united_kingdom
            animate: true
            decimals: 1
            align_state: center
            show:
             points: hover
             average: true
      

      - type: glance
        entities:   
            - binary_sensor.updater
                

      - type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.bedroom_speaker
            icon: mdi:spotify
            artwork: cover
            source: icon
            hide:
             volume: true
             source: true
             power_state: false    
          - type: custom:mini-media-player
            entity: media_player.living_room_speaker
            icon: mdi:spotify
            artwork: cover
            hide:
             volume: true
             source: true
             power_state: false     

           
  - icon: mdi:lightbulb-on
    path: Lighting 
  
  - title: Automations
    path: Automations
    cards:
    
      - type: entities
        entities: 
            - automation.leaving_work
        
  
  - icon: mdi:raspberry-pi
    path: Status
    cards:
      - type: custom:vertical-stack-in-card
        title: Hass.io Status
        cards:
            - type: entities
              entities:
                - sensor.current_version
                - sensor.uptime
                - sensor.potential_breaking_changes
                - sensor.hacs
                - sensor.last_boot
                - sensor.disk_use_home
            - type: glance
              entities:
                - sensor.processor_use
                - sensor.memory_free
                - sensor.memory_use
  
  - title: Testing
    path: Testing
    cards:
    
      - type: custom:unused-card
      
      - type: entities
        entities:
            - sun.sun
            - weather.home
            - binary_sensor.remote_ui
      
      
      
      
      
      
      
      
      
      
      